-- 055_company_sidebar_permissions.sql
INSERT INTO permissions (key, description)
VALUES
  ('company.dashboard.view', 'View company dashboard'),
  ('company.users.view', 'View company users'),
  ('company.roles.manage', 'Manage company roles and permissions'),
  ('branches.view', 'View branches'),
  ('branches.create', 'Create branches'),
  ('vendors.view', 'View vendors'),
  ('vendors.create', 'Create vendors'),
  ('callcenter.view', 'View call center'),
  ('callcenter.history.view', 'View call center history'),
  ('leads.view', 'View leads'),
  ('leads.create', 'Create leads'),
  ('inventory.view', 'View inventory'),
  ('inventory.create', 'Create inventory'),
  ('procurement.view', 'View procurement'),
  ('procurement.create', 'Create procurement'),
  ('quotes.vendor.view', 'View vendor quotes'),
  ('quotes.branch.view', 'View branch quotes'),
  ('estimates.view', 'View estimates'),
  ('estimates.create', 'Create estimates'),
  ('inspections.view', 'View inspections'),
  ('inspections.create', 'Create inspections'),
  ('jobs.view', 'View jobs'),
  ('fleet.cars.view', 'View cars'),
  ('marketing.campaigns.view', 'View marketing campaigns'),
  ('marketing.ads.view', 'View marketing ads'),
  ('marketing.sms.view', 'View marketing SMS'),
  ('marketing.email.view', 'View marketing email'),
  ('marketing.templates.view', 'View marketing templates'),
  ('marketing.social.view', 'View marketing social posts'),
  ('integrations.dialer.use', 'Use dialer integrations'),
  ('accounting.view', 'View accounting'),
  ('accounting.manage_chart', 'Manage accounting chart'),
  ('accounting.post', 'Post accounting journals'),
  ('crm.customers.view', 'View customers'),
  ('crm.customers.edit', 'Edit customers'),
  ('hr.employees.view', 'View employees'),
  ('hr.branch_users.view', 'View branch users'),
  ('hr.vendor_users.view', 'View vendor users'),
  ('reports.view', 'View reports')
ON CONFLICT (key) DO NOTHING;
