export type City = {
  countryIso2: string;
  name: string;
};

export const allCities: City[] = [
  { countryIso2: "AE", name: "Dubai" },
  { countryIso2: "AE", name: "Abu Dhabi" },
  { countryIso2: "AE", name: "Sharjah" },
  { countryIso2: "AE", name: "Ajman" },
  { countryIso2: "AE", name: "Ras Al Khaimah" },
  { countryIso2: "AE", name: "Fujairah" },
  { countryIso2: "AE", name: "Umm Al Quwain" },
  { countryIso2: "SA", name: "Riyadh" },
  { countryIso2: "SA", name: "Jeddah" },
  { countryIso2: "SA", name: "Dammam" },
  { countryIso2: "SA", name: "Medina" },
  { countryIso2: "SA", name: "Mecca" },
  { countryIso2: "OM", name: "Muscat" },
  { countryIso2: "OM", name: "Salalah" },
  { countryIso2: "QA", name: "Doha" },
  { countryIso2: "KW", name: "Kuwait City" },
  { countryIso2: "BH", name: "Manama" },
  { countryIso2: "IN", name: "Mumbai" },
  { countryIso2: "IN", name: "Delhi" },
  { countryIso2: "IN", name: "Bengaluru" },
  { countryIso2: "IN", name: "Chennai" },
  { countryIso2: "IN", name: "Ahmedabad" },
  { countryIso2: "IN", name: "Hyderabad" },
  { countryIso2: "PK", name: "Karachi" },
  { countryIso2: "PK", name: "Lahore" },
  { countryIso2: "PK", name: "Islamabad" },
  { countryIso2: "PK", name: "Rawalpindi" },
  { countryIso2: "GB", name: "London" },
  { countryIso2: "GB", name: "Manchester" },
  { countryIso2: "GB", name: "Birmingham" },
  { countryIso2: "US", name: "New York" },
  { countryIso2: "US", name: "Los Angeles" },
  { countryIso2: "US", name: "Chicago" },
  { countryIso2: "US", name: "Houston" },
  { countryIso2: "US", name: "Phoenix" },
  { countryIso2: "US", name: "Dallas" },
  { countryIso2: "US", name: "San Francisco" },
  { countryIso2: "CA", name: "Toronto" },
  { countryIso2: "CA", name: "Vancouver" },
  { countryIso2: "CA", name: "Montreal" },
  { countryIso2: "DE", name: "Berlin" },
  { countryIso2: "DE", name: "Munich" },
  { countryIso2: "FR", name: "Paris" },
  { countryIso2: "FR", name: "Lyon" },
  { countryIso2: "AU", name: "Sydney" },
  { countryIso2: "AU", name: "Melbourne" },
  { countryIso2: "NZ", name: "Auckland" },
  { countryIso2: "CN", name: "Beijing" },
  { countryIso2: "CN", name: "Shanghai" },
  { countryIso2: "JP", name: "Tokyo" },
  { countryIso2: "JP", name: "Osaka" },
  { countryIso2: "KR", name: "Seoul" },
  { countryIso2: "BR", name: "São Paulo" },
  { countryIso2: "BR", name: "Rio de Janeiro" },
  { countryIso2: "ZA", name: "Johannesburg" },
  { countryIso2: "NG", name: "Lagos" },
  { countryIso2: "EG", name: "Cairo" },
  { countryIso2: "KE", name: "Nairobi" },
  { countryIso2: "AR", name: "Buenos Aires" },
  { countryIso2: "MX", name: "Mexico City" },
  { countryIso2: "ES", name: "Madrid" },
  { countryIso2: "ES", name: "Barcelona" },
];

export function citiesForCountry(iso2: string): City[] {
  return allCities.filter((c) => c.countryIso2 === iso2);
}
