export type State = {
  countryIso2: string;
  code: string;
  name: string;
};

export const allStates: State[] = [
  { countryIso2: "AE", code: "DU", name: "Dubai" },
  { countryIso2: "AE", code: "AD", name: "Abu Dhabi" },
  { countryIso2: "AE", code: "SH", name: "Sharjah" },
  { countryIso2: "AE", code: "AJ", name: "Ajman" },
  { countryIso2: "AE", code: "RAK", name: "Ras Al Khaimah" },
  { countryIso2: "AE", code: "FJ", name: "Fujairah" },
  { countryIso2: "AE", code: "UAQ", name: "Umm Al Quwain" },
  { countryIso2: "SA", code: "RI", name: "Riyadh" },
  { countryIso2: "SA", code: "ME", name: "Makkah" },
  { countryIso2: "SA", code: "MD", name: "Madinah" },
  { countryIso2: "SA", code: "EA", name: "Eastern Province" },
  { countryIso2: "SA", code: "QA", name: "Qassim" },
  { countryIso2: "SA", code: "TB", name: "Tabuk" },
  { countryIso2: "OM", code: "MA", name: "Muscat" },
  { countryIso2: "OM", code: "DH", name: "Dhofar" },
  { countryIso2: "OM", code: "DA", name: "Al Dakhiliyah" },
  { countryIso2: "QA", code: "DA", name: "Ad Dawhah" },
  { countryIso2: "QA", code: "RA", name: "Al Rayyan" },
  { countryIso2: "KW", code: "KU", name: "Al Asimah" },
  { countryIso2: "KW", code: "AH", name: "Al Ahmadi" },
  { countryIso2: "BH", code: "SG", name: "Central" },
  { countryIso2: "BH", code: "MU", name: "Muharraq" },
  { countryIso2: "IN", code: "DL", name: "Delhi" },
  { countryIso2: "IN", code: "MH", name: "Maharashtra" },
  { countryIso2: "IN", code: "KA", name: "Karnataka" },
  { countryIso2: "IN", code: "TN", name: "Tamil Nadu" },
  { countryIso2: "IN", code: "GJ", name: "Gujarat" },
  { countryIso2: "IN", code: "UP", name: "Uttar Pradesh" },
  { countryIso2: "IN", code: "RJ", name: "Rajasthan" },
  { countryIso2: "PK", code: "SD", name: "Sindh" },
  { countryIso2: "PK", code: "PB", name: "Punjab" },
  { countryIso2: "PK", code: "KP", name: "Khyber Pakhtunkhwa" },
  { countryIso2: "PK", code: "BA", name: "Balochistan" },
  { countryIso2: "GB", code: "ENG", name: "England" },
  { countryIso2: "GB", code: "SCT", name: "Scotland" },
  { countryIso2: "GB", code: "WLS", name: "Wales" },
  { countryIso2: "GB", code: "NIR", name: "Northern Ireland" },
  { countryIso2: "US", code: "AL", name: "Alabama" },
  { countryIso2: "US", code: "AK", name: "Alaska" },
  { countryIso2: "US", code: "AZ", name: "Arizona" },
  { countryIso2: "US", code: "AR", name: "Arkansas" },
  { countryIso2: "US", code: "CA", name: "California" },
  { countryIso2: "US", code: "CO", name: "Colorado" },
  { countryIso2: "US", code: "CT", name: "Connecticut" },
  { countryIso2: "US", code: "DE", name: "Delaware" },
  { countryIso2: "US", code: "FL", name: "Florida" },
  { countryIso2: "US", code: "GA", name: "Georgia" },
  { countryIso2: "US", code: "HI", name: "Hawaii" },
  { countryIso2: "US", code: "ID", name: "Idaho" },
  { countryIso2: "US", code: "IL", name: "Illinois" },
  { countryIso2: "US", code: "IN", name: "Indiana" },
  { countryIso2: "US", code: "IA", name: "Iowa" },
  { countryIso2: "US", code: "KS", name: "Kansas" },
  { countryIso2: "US", code: "KY", name: "Kentucky" },
  { countryIso2: "US", code: "LA", name: "Louisiana" },
  { countryIso2: "US", code: "ME", name: "Maine" },
  { countryIso2: "US", code: "MD", name: "Maryland" },
  { countryIso2: "US", code: "MA", name: "Massachusetts" },
  { countryIso2: "US", code: "MI", name: "Michigan" },
  { countryIso2: "US", code: "MN", name: "Minnesota" },
  { countryIso2: "US", code: "MS", name: "Mississippi" },
  { countryIso2: "US", code: "MO", name: "Missouri" },
  { countryIso2: "US", code: "MT", name: "Montana" },
  { countryIso2: "US", code: "NE", name: "Nebraska" },
  { countryIso2: "US", code: "NV", name: "Nevada" },
  { countryIso2: "US", code: "NH", name: "New Hampshire" },
  { countryIso2: "US", code: "NJ", name: "New Jersey" },
  { countryIso2: "US", code: "NM", name: "New Mexico" },
  { countryIso2: "US", code: "NY", name: "New York" },
  { countryIso2: "US", code: "NC", name: "North Carolina" },
  { countryIso2: "US", code: "ND", name: "North Dakota" },
  { countryIso2: "US", code: "OH", name: "Ohio" },
  { countryIso2: "US", code: "OK", name: "Oklahoma" },
  { countryIso2: "US", code: "OR", name: "Oregon" },
  { countryIso2: "US", code: "PA", name: "Pennsylvania" },
  { countryIso2: "US", code: "RI", name: "Rhode Island" },
  { countryIso2: "US", code: "SC", name: "South Carolina" },
  { countryIso2: "US", code: "SD", name: "South Dakota" },
  { countryIso2: "US", code: "TN", name: "Tennessee" },
  { countryIso2: "US", code: "TX", name: "Texas" },
  { countryIso2: "US", code: "UT", name: "Utah" },
  { countryIso2: "US", code: "VT", name: "Vermont" },
  { countryIso2: "US", code: "VA", name: "Virginia" },
  { countryIso2: "US", code: "WA", name: "Washington" },
  { countryIso2: "US", code: "WV", name: "West Virginia" },
  { countryIso2: "US", code: "WI", name: "Wisconsin" },
  { countryIso2: "US", code: "WY", name: "Wyoming" },
  { countryIso2: "CA", code: "AB", name: "Alberta" },
  { countryIso2: "CA", code: "BC", name: "British Columbia" },
  { countryIso2: "CA", code: "MB", name: "Manitoba" },
  { countryIso2: "CA", code: "NB", name: "New Brunswick" },
  { countryIso2: "CA", code: "NL", name: "Newfoundland and Labrador" },
  { countryIso2: "CA", code: "NS", name: "Nova Scotia" },
  { countryIso2: "CA", code: "ON", name: "Ontario" },
  { countryIso2: "CA", code: "PE", name: "Prince Edward Island" },
  { countryIso2: "CA", code: "QC", name: "Quebec" },
  { countryIso2: "CA", code: "SK", name: "Saskatchewan" },
  { countryIso2: "CA", code: "NT", name: "Northwest Territories" },
  { countryIso2: "CA", code: "NU", name: "Nunavut" },
  { countryIso2: "CA", code: "YT", name: "Yukon" },
];

export function statesForCountry(iso2: string): State[] {
  if (!iso2) return [];
  return allStates.filter((s) => s.countryIso2 === iso2);
}
