-- Refresh inventory car makes/models from car_details.json (global scope)

CREATE TEMP TABLE inventory_car_seed (make text NOT NULL, model text NOT NULL);

INSERT INTO inventory_car_seed (make, model) VALUES

  ('ABARTH', '1000 OTR BERLINETTA BERTONE'),
  ('ABARTH', '1000 SP'),
  ('ABARTH', '1100 SCORPIONE SPIDER (BOANO)'),
  ('ABARTH', '124 SPIDER'),
  ('ABARTH', '1500 BIPOSTO'),
  ('ABARTH', '204A'),
  ('ABARTH', '205A BERLINETTA'),
  ('ABARTH', '207A SPYDER CORSA BOANO'),
  ('ABARTH', '208A SPYDER BOANO'),
  ('ABARTH', '209A COUPE BOANO'),
  ('ABARTH', '210A SPYDER BOANO'),
  ('ABARTH', '215A COUPE BERTONE'),
  ('ABARTH', '216A SPYDER BERTONE'),
  ('ABARTH', '3000 PROTOTIPO'),
  ('ABARTH', '500'),
  ('ABARTH', '595'),
  ('ABARTH', '695'),
  ('ABARTH', '750'),
  ('ABARTH', '750 SPIDER ALLEMANO'),
  ('ABARTH', 'MONOMILLE'),
  ('ABARTH', 'OT 1300'),
  ('ABARTH', 'ZAGATO'),
  ('AC', '2-LITRE'),
  ('AC', '3000ME'),
  ('AC', 'ACE'),
  ('AC', 'ACECA'),
  ('AC', 'BROOKLANDS ACE'),
  ('AC', 'COBRA'),
  ('AC', 'DAX COBRA'),
  ('AC', 'FRUA'),
  ('AC', 'GREYHOUND'),
  ('AC', 'GT ZAGATO'),
  ('AC', 'MARK IV'),
  ('AC', 'MK VI'),
  ('AC', 'PETITE'),
  ('AC', 'SOCIABLE'),
  ('ACURA', 'ILX'),
  ('ACURA', 'INTEGRA - GEN1'),
  ('ACURA', 'INTEGRA - GEN2'),
  ('ACURA', 'INTEGRA - GEN3'),
  ('ACURA', 'INTEGRA - GEN4'),
  ('ACURA', 'INTEGRA - GEN5'),
  ('ACURA', 'LEGEND - GEN1'),
  ('ACURA', 'LEGEND - GEN2'),
  ('ACURA', 'MDX - GEN1'),
  ('ACURA', 'MDX - GEN2'),
  ('ACURA', 'MDX - GEN3'),
  ('ACURA', 'MDX - GEN4'),
  ('ACURA', 'MDX TYPE S'),
  ('ACURA', 'NSX - GEN1'),
  ('ACURA', 'NSX - GEN2'),
  ('ACURA', 'NSX TYPE S'),
  ('ACURA', 'RDX - GEN1'),
  ('ACURA', 'RDX - GEN2'),
  ('ACURA', 'RDX - GEN3'),
  ('ACURA', 'RL - GEN1'),
  ('ACURA', 'RL - GEN2'),
  ('ACURA', 'RLX - GEN1'),
  ('ACURA', 'TL - GEN1'),
  ('ACURA', 'TL - GEN2'),
  ('ACURA', 'TL - GEN3'),
  ('ACURA', 'TL - GEN4'),
  ('ACURA', 'TLX - GEN1'),
  ('ACURA', 'TLX - GEN2'),
  ('ACURA', 'TLX TYPE S'),
  ('ACURA', 'TSX - GEN1'),
  ('ACURA', 'TSX - GEN2'),
  ('ACURA', 'ZDX - GEN1'),
  ('ACURA', 'ZDX - GEN2'),
  ('ACURA', 'ZDX TYPE S'),
  ('AIWAYS', 'U5'),
  ('AIWAYS', 'U6'),
  ('AIWAYS', 'U7'),
  ('AIXAM', '400'),
  ('AIXAM', '500'),
  ('AIXAM', '500.4'),
  ('AIXAM', 'A721'),
  ('AIXAM', 'A741'),
  ('AIXAM', 'CITY'),
  ('AIXAM', 'COUPE'),
  ('AIXAM', 'CROSSLINE'),
  ('AIXAM', 'ECITY'),
  ('AIXAM', 'ECOUPE'),
  ('AIXAM', 'GTO'),
  ('AIXAM', 'MEGA'),
  ('AIXAM', 'PRO D-TRUCK'),
  ('AIXAM', 'PRO D-TRUCK ELECTRIC'),
  ('AIXAM', 'SCOUTY'),
  ('AK', 'COBRA 289'),
  ('AK', 'COBRA 427'),
  ('AK', 'COBRA 427 S/C'),
  ('ALFA ROMEO', '145'),
  ('ALFA ROMEO', '147'),
  ('ALFA ROMEO', '156'),
  ('ALFA ROMEO', '159'),
  ('ALFA ROMEO', '166'),
  ('ALFA ROMEO', '4C'),
  ('ALFA ROMEO', '8C COMPETIZIONE'),
  ('ALFA ROMEO', 'ALFASUD'),
  ('ALFA ROMEO', 'BRERA'),
  ('ALFA ROMEO', 'GIULIA'),
  ('ALFA ROMEO', 'GIULIETTA'),
  ('ALFA ROMEO', 'GTV'),
  ('ALFA ROMEO', 'MITO'),
  ('ALFA ROMEO', 'SPIDER'),
  ('ALFA ROMEO', 'STELVIO'),
  ('ALFA ROMEO', 'TONALE'),
  ('ALPINA', 'B10 E34'),
  ('ALPINA', 'B12 E32/E38'),
  ('ALPINA', 'B3 E30'),
  ('ALPINA', 'B3 E36'),
  ('ALPINA', 'B3 E46'),
  ('ALPINA', 'B3 E90/E91/E92/E93'),
  ('ALPINA', 'B3 F30/F31'),
  ('ALPINA', 'B3 G20/G21'),
  ('ALPINA', 'B4 F32/F33'),
  ('ALPINA', 'B5 E60/E61'),
  ('ALPINA', 'B5 F10/F11'),
  ('ALPINA', 'B5 G30/G31'),
  ('ALPINA', 'B6 E63/E64'),
  ('ALPINA', 'B6 F12'),
  ('ALPINA', 'B7 E65/E66'),
  ('ALPINA', 'B7 F01/F02'),
  ('ALPINA', 'B8 E31'),
  ('ALPINA', 'C1 E21/E30'),
  ('ALPINA', 'D3 F30'),
  ('ALPINA', 'ROADSTER S E85'),
  ('ALPINA', 'XB7 G07'),
  ('ALPINA', 'XD3 G01'),
  ('ALPINA', 'XD4 G02'),
  ('ALPINA', 'Z8 E52 ROADSTER V8'),
  ('ALPINE', 'A106'),
  ('ALPINE', 'A108'),
  ('ALPINE', 'A110'),
  ('ALPINE', 'A110 (19621977)'),
  ('ALPINE', 'A110 E-TERNITE CONCEPT'),
  ('ALPINE', 'A110 GT4'),
  ('ALPINE', 'A110 RALLY'),
  ('ALPINE', 'A110-50 CONCEPT'),
  ('ALPINE', 'A290'),
  ('ALPINE', 'A290_ CONCEPT'),
  ('ALPINE', 'A310'),
  ('ALPINE', 'A390'),
  ('ALPINE', 'A390_ CONCEPT'),
  ('ALPINE', 'A610'),
  ('ALPINE', 'ALPENGLOW CONCEPT'),
  ('ALPINE', 'ALPINE VISION GRAN TURISMO'),
  ('ALPINE', 'GTA'),
  ('ALVIS', '12/50'),
  ('ALVIS', '14/40'),
  ('ALVIS', '3 LITRE'),
  ('ALVIS', '3 LITRE SERIES 2'),
  ('ALVIS', '4.0 LITRE'),
  ('ALVIS', '4.3 LITRE'),
  ('ALVIS', 'SARACEN'),
  ('ALVIS', 'SPEED 20'),
  ('ALVIS', 'SPEED 25'),
  ('ALVIS', 'STALWART'),
  ('ALVIS', 'TA 14'),
  ('ALVIS', 'TC 21/100'),
  ('ALVIS', 'TD 21'),
  ('ALVIS', 'TE 21'),
  ('ARIEL', '500'),
  ('ARIEL', 'ACE'),
  ('ARIEL', 'ANDERE'),
  ('ARIEL', 'ATOM'),
  ('ARIEL', 'ATOM 2'),
  ('ARIEL', 'ATOM 3'),
  ('ARIEL', 'ATOM 3.5'),
  ('ARIEL', 'ATOM 3.5R'),
  ('ARIEL', 'ATOM 3S'),
  ('ARIEL', 'ATOM 4'),
  ('ARIEL', 'ATOM 4R'),
  ('ARIEL', 'ATOM V8'),
  ('ARIEL', 'NOMAD'),
  ('ARIEL', 'NOMAD R'),
  ('ARIEL', 'TWITE'),
  ('ARO', '10'),
  ('ARO', '10.4'),
  ('ARO', '240'),
  ('ARO', '240 4X4'),
  ('ARO', '240 SPECIAL'),
  ('ARO', '242'),
  ('ARO', '243'),
  ('ARO', '243 DOKA'),
  ('ARO', '243 VAN'),
  ('ARO', '244'),
  ('ARO', '244 DACIA'),
  ('ARO', '244 MILITARY'),
  ('ARO', '310'),
  ('ARO', '310 MILITARY'),
  ('ARO', '320'),
  ('ARO', '320 PICK-UP'),
  ('ARO', '330'),
  ('ARO', '330 4X4'),
  ('ARO', '330 VAN'),
  ('ARO', '332'),
  ('ARO', 'DRAGON'),
  ('ARO', 'M461'),
  ('ARO', 'SPARTANA'),
  ('ARTEGA', 'ANDERE'),
  ('ARTEGA', 'GT'),
  ('ARTEGA', 'KARO-ISETTA'),
  ('ARTEGA', 'SCALO'),
  ('ARTEGA', 'SCALO SUPERELLETRA'),
  ('ARTEGA', 'SE'),
  ('ASIA MOTORS', 'ANDERE'),
  ('ASIA MOTORS', 'CERES'),
  ('ASIA MOTORS', 'COMBI'),
  ('ASIA MOTORS', 'COSMOS'),
  ('ASIA MOTORS', 'F-SERIES'),
  ('ASIA MOTORS', 'FIAT 124'),
  ('ASIA MOTORS', 'GRAN BIRD'),
  ('ASIA MOTORS', 'GRANTO'),
  ('ASIA MOTORS', 'HILLUX'),
  ('ASIA MOTORS', 'KM900 APC'),
  ('ASIA MOTORS', 'RETONA'),
  ('ASIA MOTORS', 'ROCSTA'),
  ('ASIA MOTORS', 'TIGER'),
  ('ASIA MOTORS', 'TOPIC'),
  ('ASIA MOTORS', 'TOWNER'),
  ('ASTON MARTIN', 'AR1'),
  ('ASTON MARTIN', 'BULLDOG'),
  ('ASTON MARTIN', 'CYGNET'),
  ('ASTON MARTIN', 'DB1'),
  ('ASTON MARTIN', 'DB11'),
  ('ASTON MARTIN', 'DB12'),
  ('ASTON MARTIN', 'DB2'),
  ('ASTON MARTIN', 'DB2/4'),
  ('ASTON MARTIN', 'DB3'),
  ('ASTON MARTIN', 'DB3S'),
  ('ASTON MARTIN', 'DB4'),
  ('ASTON MARTIN', 'DB5'),
  ('ASTON MARTIN', 'DB6'),
  ('ASTON MARTIN', 'DB7'),
  ('ASTON MARTIN', 'DB7 VANTAGE'),
  ('ASTON MARTIN', 'DB7 ZAGATO'),
  ('ASTON MARTIN', 'DB9'),
  ('ASTON MARTIN', 'DB9 VOLANTE'),
  ('ASTON MARTIN', 'DBS (20072012)'),
  ('ASTON MARTIN', 'DBS (CLASSIC)'),
  ('ASTON MARTIN', 'DBS SUPERLEGGERA'),
  ('ASTON MARTIN', 'DBS VOLANTE'),
  ('ASTON MARTIN', 'DBX'),
  ('ASTON MARTIN', 'LAGONDA'),
  ('ASTON MARTIN', 'LAGONDA TARAF'),
  ('ASTON MARTIN', 'LAGONDA VISION CONCEPT'),
  ('ASTON MARTIN', 'ONE-77'),
  ('ASTON MARTIN', 'RAPIDE'),
  ('ASTON MARTIN', 'RAPIDE S'),
  ('ASTON MARTIN', 'V12 VANTAGE'),
  ('ASTON MARTIN', 'V8 VANTAGE (19771989)'),
  ('ASTON MARTIN', 'V8 VANTAGE (20052017)'),
  ('ASTON MARTIN', 'V8 VANTAGE (2018)'),
  ('ASTON MARTIN', 'VALHALLA'),
  ('ASTON MARTIN', 'VALKYRIE'),
  ('ASTON MARTIN', 'VANQUISH (20012007)'),
  ('ASTON MARTIN', 'VANQUISH (20122018)'),
  ('ASTON MARTIN', 'VANQUISH ZAGATO'),
  ('ASTON MARTIN', 'VANTAGE (CLASSIC)'),
  ('ASTON MARTIN', 'VICTOR'),
  ('ASTON MARTIN', 'VIRAGE'),
  ('ASTON MARTIN', 'VIRAGE (20112012)'),
  ('ASTON MARTIN', 'VULCAN'),
  ('AUDI', '50'),
  ('AUDI', 'A3 CABRIOLET 8P'),
  ('AUDI', 'A3 CABRIOLET 8V'),
  ('AUDI', 'A4 ALLROAD B8'),
  ('AUDI', 'A4 ALLROAD B9'),
  ('AUDI', 'A4 AVANT B5'),
  ('AUDI', 'A4 AVANT B6'),
  ('AUDI', 'A4 AVANT B7'),
  ('AUDI', 'A4 AVANT B8'),
  ('AUDI', 'A4 AVANT B9'),
  ('AUDI', 'A4 CABRIOLET B6/B7'),
  ('AUDI', 'A5 8T (B8)'),
  ('AUDI', 'A5 F5 (B9)'),
  ('AUDI', 'A6 ALLROAD C5'),
  ('AUDI', 'A6 ALLROAD C6'),
  ('AUDI', 'A6 ALLROAD C7'),
  ('AUDI', 'A6 ALLROAD C8'),
  ('AUDI', 'A6 C4'),
  ('AUDI', 'A6 C5'),
  ('AUDI', 'A6 C6'),
  ('AUDI', 'A6 C7'),
  ('AUDI', 'A6 C8'),
  ('AUDI', 'A7 4G8 (C7)'),
  ('AUDI', 'A7 4K8 (C8)'),
  ('AUDI', 'A8 D2'),
  ('AUDI', 'A8 D3'),
  ('AUDI', 'A8 D4'),
  ('AUDI', 'A8 D5'),
  ('AUDI', 'AUDI QUATTRO'),
  ('AUDI', 'E-TRON (GE)'),
  ('AUDI', 'E-TRON (SUV)'),
  ('AUDI', 'E-TRON GT'),
  ('AUDI', 'E-TRON SPORTBACK'),
  ('AUDI', 'Q2 (GA)'),
  ('AUDI', 'Q2 GA'),
  ('AUDI', 'Q3 (8U)'),
  ('AUDI', 'Q3 (F3)'),
  ('AUDI', 'Q3 8U'),
  ('AUDI', 'Q3 F3'),
  ('AUDI', 'Q4 E-TRON'),
  ('AUDI', 'Q4 SPORTBACK E-TRON'),
  ('AUDI', 'Q5 (8R)'),
  ('AUDI', 'Q5 (FY)'),
  ('AUDI', 'Q5 8R'),
  ('AUDI', 'Q5 FY'),
  ('AUDI', 'Q7 (4L)'),
  ('AUDI', 'Q7 (4M)'),
  ('AUDI', 'Q7 4L'),
  ('AUDI', 'Q7 4M'),
  ('AUDI', 'Q8 (4M)'),
  ('AUDI', 'Q8 4M'),
  ('AUDI', 'Q8 E-TRON'),
  ('AUDI', 'R8 (TYPE 42)'),
  ('AUDI', 'R8 (TYPE 4S)'),
  ('AUDI', 'R8 42 (GEN1)'),
  ('AUDI', 'R8 4S (GEN2)'),
  ('AUDI', 'RS E-TRON GT'),
  ('AUDI', 'RS Q3 (8U)'),
  ('AUDI', 'RS Q3 (F3)'),
  ('AUDI', 'RS Q3 8U'),
  ('AUDI', 'RS Q3 F3'),
  ('AUDI', 'RS Q5'),
  ('AUDI', 'RS Q5 (CONCEPT)'),
  ('AUDI', 'RS Q8 (4M)'),
  ('AUDI', 'RS Q8 4M'),
  ('AUDI', 'RS3 (8P)'),
  ('AUDI', 'RS3 (8V)'),
  ('AUDI', 'RS3 (8Y)'),
  ('AUDI', 'RS4 AVANT (B8)'),
  ('AUDI', 'RS4 AVANT (B9)'),
  ('AUDI', 'RS4 AVANT B5'),
  ('AUDI', 'RS4 AVANT B7'),
  ('AUDI', 'RS4 AVANT B8'),
  ('AUDI', 'RS4 AVANT B9'),
  ('AUDI', 'RS5 (B8)'),
  ('AUDI', 'RS5 (B9)'),
  ('AUDI', 'RS5 8T (B8)'),
  ('AUDI', 'RS5 F5 (B9)'),
  ('AUDI', 'RS6 AVANT (C5)'),
  ('AUDI', 'RS6 AVANT (C6)'),
  ('AUDI', 'RS6 AVANT (C7)'),
  ('AUDI', 'RS6 AVANT (C8)'),
  ('AUDI', 'RS6 C5'),
  ('AUDI', 'RS6 C6'),
  ('AUDI', 'RS6 C7'),
  ('AUDI', 'RS6 C8'),
  ('AUDI', 'RS7 (C7)'),
  ('AUDI', 'RS7 (C8)'),
  ('AUDI', 'RS7 4G8 (C7)'),
  ('AUDI', 'RS7 4K8 (C8)'),
  ('AUDI', 'S3 (8L)'),
  ('AUDI', 'S3 (8P)'),
  ('AUDI', 'S3 (8V)'),
  ('AUDI', 'S3 (8Y)'),
  ('AUDI', 'S4 (B6)'),
  ('AUDI', 'S4 (B8)'),
  ('AUDI', 'S4 (B9)'),
  ('AUDI', 'S4 AVANT B5'),
  ('AUDI', 'S5 (B8)'),
  ('AUDI', 'S5 (B9)'),
  ('AUDI', 'S5 8T (B8)'),
  ('AUDI', 'S5 F5 (B9)'),
  ('AUDI', 'S6 (C5)'),
  ('AUDI', 'S6 (C6)'),
  ('AUDI', 'S6 (C7)'),
  ('AUDI', 'S6 (C8)'),
  ('AUDI', 'S6 C4'),
  ('AUDI', 'S6 C5'),
  ('AUDI', 'S6 C6'),
  ('AUDI', 'S6 C7'),
  ('AUDI', 'S6 C8'),
  ('AUDI', 'S7 (C7)'),
  ('AUDI', 'S7 4G8 (C7)'),
  ('AUDI', 'S7 4K8 (C8)'),
  ('AUDI', 'S8 D2'),
  ('AUDI', 'S8 D3'),
  ('AUDI', 'S8 D4'),
  ('AUDI', 'S8 D5'),
  ('AUDI', 'SQ2 GA'),
  ('AUDI', 'SQ5 (8R)'),
  ('AUDI', 'SQ5 (FY)'),
  ('AUDI', 'SQ5 8R'),
  ('AUDI', 'SQ5 FY'),
  ('AUDI', 'SQ7 (4M)'),
  ('AUDI', 'SQ7 4M'),
  ('AUDI', 'SQ8 (4M)'),
  ('AUDI', 'SQ8 4M'),
  ('AUDI', 'TT (8J)'),
  ('AUDI', 'TT (8N)'),
  ('AUDI', 'TT (FV/8S)'),
  ('AUDI', 'TT 8J (MK2)'),
  ('AUDI', 'TT 8N (MK1)'),
  ('AUDI', 'TT FV/8S (MK3)'),
  ('AUDI', 'TT RS 8J (MK2)'),
  ('AUDI', 'TT RS FV/8S (MK3)'),
  ('AUDI', 'TTS 8J (MK2)'),
  ('AUDI', 'TTS FV/8S (MK3)'),
  ('AUDI', 'V8 D11'),
  ('AUSTIN', '10'),
  ('AUSTIN', '12'),
  ('AUSTIN', '16'),
  ('AUSTIN', '18'),
  ('AUSTIN', '20'),
  ('AUSTIN', '28'),
  ('AUSTIN', '7'),
  ('AUSTIN', '8'),
  ('AUSTIN', 'A110 WESTMINSTER'),
  ('AUSTIN', 'A30'),
  ('AUSTIN', 'A35'),
  ('AUSTIN', 'A40'),
  ('AUSTIN', 'A40 DEVON'),
  ('AUSTIN', 'A40 FARINA'),
  ('AUSTIN', 'A40 SOMERSET'),
  ('AUSTIN', 'A40 SPORTS'),
  ('AUSTIN', 'A50 CAMBRIDGE'),
  ('AUSTIN', 'A55 CAMBRIDGE'),
  ('AUSTIN', 'A60 CAMBRIDGE'),
  ('AUSTIN', 'A70 HAMPSHIRE'),
  ('AUSTIN', 'A70 HEREFORD'),
  ('AUSTIN', 'A90 ATLANTIC'),
  ('AUSTIN', 'A99 WESTMINSTER'),
  ('AUSTIN', 'ALLEGRO'),
  ('AUSTIN', 'AMBASSADOR'),
  ('AUSTIN', 'AMBULANCE'),
  ('AUSTIN', 'CAMBRIDGE'),
  ('AUSTIN', 'COUNTRYMAN'),
  ('AUSTIN', 'DEVON'),
  ('AUSTIN', 'FX4 TAXI'),
  ('AUSTIN', 'GYPSY'),
  ('AUSTIN', 'HEALEY 100'),
  ('AUSTIN', 'HEALEY 3000'),
  ('AUSTIN', 'HEALEY SPRITE'),
  ('AUSTIN', 'MAESTRO'),
  ('AUSTIN', 'MAXI'),
  ('AUSTIN', 'METRO'),
  ('AUSTIN', 'MINI'),
  ('AUSTIN', 'MINI COOPER S'),
  ('AUSTIN', 'MINI MOKE'),
  ('AUSTIN', 'PRINCESS'),
  ('AUSTIN', 'PRINCESS LIMOUSINE'),
  ('AUSTIN', 'SARACEN'),
  ('AUSTIN', 'SEVEN'),
  ('AUSTIN', 'SHEERLINE'),
  ('AUSTIN', 'SPRITE'),
  ('AUSTIN', 'TEN'),
  ('AUSTIN', 'TWELVE'),
  ('AUTO UNION', '1000'),
  ('AUTO UNION', '1000 COUPE'),
  ('AUTO UNION', '1000 LIMOUSINE'),
  ('AUTO UNION', '1000 S'),
  ('AUTO UNION', '1000 SP'),
  ('AUTO UNION', '1000 UNIVERSAL'),
  ('AUTO UNION', 'F102'),
  ('AUTO UNION', 'F11'),
  ('AUTO UNION', 'F12'),
  ('AUTO UNION', 'TYPE A'),
  ('AUTO UNION', 'TYPE B'),
  ('AUTO UNION', 'TYPE C'),
  ('AUTO UNION', 'TYPE D'),
  ('AUTOBIANCHI', 'A111'),
  ('AUTOBIANCHI', 'A112'),
  ('AUTOBIANCHI', 'A112 ABARTH'),
  ('AUTOBIANCHI', 'A112 ELITE'),
  ('AUTOBIANCHI', 'A112 GIOVANI (KONCEPCIO)'),
  ('AUTOBIANCHI', 'A112 JUNIOR'),
  ('AUTOBIANCHI', 'BIANCHINA BERLINA'),
  ('AUTOBIANCHI', 'BIANCHINA CABRIOLET'),
  ('AUTOBIANCHI', 'BIANCHINA FURGONCINO'),
  ('AUTOBIANCHI', 'BIANCHINA PANORAMICA'),
  ('AUTOBIANCHI', 'BIANCHINA TRASFORMABILE'),
  ('AUTOBIANCHI', 'ESTENSE'),
  ('AUTOBIANCHI', 'FILARETE'),
  ('AUTOBIANCHI', 'FIUMARO'),
  ('AUTOBIANCHI', 'G31'),
  ('AUTOBIANCHI', 'PRIMULA 2-DOOR'),
  ('AUTOBIANCHI', 'PRIMULA 3-DOOR'),
  ('AUTOBIANCHI', 'PRIMULA 4-DOOR'),
  ('AUTOBIANCHI', 'PRIMULA COUPE'),
  ('AUTOBIANCHI', 'RUNABOUT'),
  ('AUTOBIANCHI', 'SCALIGERO'),
  ('AUTOBIANCHI', 'STELLINA'),
  ('AUTOBIANCHI', 'VISCONTEO'),
  ('AUTOBIANCHI', 'Y10'),
  ('BAC', 'MONO'),
  ('BAC', 'MONO F'),
  ('BAC', 'MONO ONE'),
  ('BAC', 'MONO R'),
  ('BAC', 'MONO X'),
  ('BAIC', 'BEIJING BJ20'),
  ('BAIC', 'BEIJING BJ30'),
  ('BAIC', 'BEIJING BJ40'),
  ('BAIC', 'BEIJING BJ60'),
  ('BAIC', 'BEIJING EC3'),
  ('BAIC', 'BEIJING EC5'),
  ('BAIC', 'BEIJING EU5'),
  ('BAIC', 'BEIJING EU7'),
  ('BAIC', 'BEIJING EX3'),
  ('BAIC', 'BEIJING U5'),
  ('BAIC', 'BEIJING U7'),
  ('BAIC', 'BEIJING X35'),
  ('BAIC', 'BEIJING X55'),
  ('BAIC', 'BEIJING X7'),
  ('BAIC', 'BEIJING X75'),
  ('BAIC', 'SENOVA D20'),
  ('BAIC', 'SENOVA D50'),
  ('BAIC', 'SENOVA D60'),
  ('BAIC', 'SENOVA D70'),
  ('BAIC', 'SENOVA D80'),
  ('BAIC', 'SENOVA X25'),
  ('BAIC', 'SENOVA X35'),
  ('BAIC', 'SENOVA X55'),
  ('BAIC', 'SENOVA X55-II'),
  ('BAIC', 'SENOVA X65'),
  ('BAIC', 'WEIWANG M20'),
  ('BAIC', 'WEIWANG M50F'),
  ('BAIC', 'WEIWANG S50'),
  ('BARKAS', 'B1000'),
  ('BARKAS', 'B1000 BUS'),
  ('BARKAS', 'B1000 KASTENWAGEN'),
  ('BARKAS', 'B1000 KRANKENWAGEN'),
  ('BARKAS', 'B1000 PRITSCHE'),
  ('BARKAS', 'B1000-1'),
  ('BARKAS', 'B1100'),
  ('BARKAS', 'FRAMO V901/2'),
  ('BARKAS', 'V902'),
  ('BARKAS', 'V903'),
  ('BEAUFORD', 'SERIES 3'),
  ('BEAUFORD', 'SERIES 3 HARD TOP'),
  ('BEAUFORD', 'SERIES 3 LIMOUSINE'),
  ('BEAUFORD', 'SERIES 3 OPEN TOURER'),
  ('BEAUFORD', 'SERIES 3 SEDANCA DE VILLE'),
  ('BEAUFORD', 'SERIES 3 SOFT TOP'),
  ('BENTLEY', '3 LITRE'),
  ('BENTLEY', '412 LITRE'),
  ('BENTLEY', '612 LITRE'),
  ('BENTLEY', '8 LITRE'),
  ('BENTLEY', 'ARNAGE'),
  ('BENTLEY', 'AZURE'),
  ('BENTLEY', 'BACALAR'),
  ('BENTLEY', 'BENTAYGA'),
  ('BENTLEY', 'BLOWER BENTLEY'),
  ('BENTLEY', 'BROOKLANDS'),
  ('BENTLEY', 'CONTINENTAL'),
  ('BENTLEY', 'CONTINENTAL FLYING SPUR'),
  ('BENTLEY', 'CONTINENTAL GT'),
  ('BENTLEY', 'CONTINENTAL GT SPEED'),
  ('BENTLEY', 'CONTINENTAL GTC'),
  ('BENTLEY', 'CONTINENTAL R'),
  ('BENTLEY', 'CONTINENTAL S'),
  ('BENTLEY', 'CONTINENTAL SUPERSPORTS'),
  ('BENTLEY', 'CONTINENTAL T'),
  ('BENTLEY', 'CORNICHE'),
  ('BENTLEY', 'EIGHT'),
  ('BENTLEY', 'EXP 10 SPEED 6'),
  ('BENTLEY', 'EXP 100 GT'),
  ('BENTLEY', 'FLYING SPUR'),
  ('BENTLEY', 'MARK VI'),
  ('BENTLEY', 'MULSANNE'),
  ('BENTLEY', 'R TYPE'),
  ('BENTLEY', 'S1'),
  ('BENTLEY', 'S2'),
  ('BENTLEY', 'S3'),
  ('BENTLEY', 'SPEED SIX'),
  ('BENTLEY', 'STATE LIMOUSINE'),
  ('BENTLEY', 'T-SERIES'),
  ('BENTLEY', 'TURBO R'),
  ('BENTLEY', 'TURBO RT'),
  ('BERTONE', 'BARCHETTA'),
  ('BERTONE', 'BAT 11'),
  ('BERTONE', 'BAT 5'),
  ('BERTONE', 'BAT 7'),
  ('BERTONE', 'BAT 9'),
  ('BERTONE', 'BIRUSA'),
  ('BERTONE', 'BLITZ'),
  ('BERTONE', 'ENDURO'),
  ('BERTONE', 'GB110'),
  ('BERTONE', 'GENESIS'),
  ('BERTONE', 'MANTIDE'),
  ('BERTONE', 'NAVAJO'),
  ('BERTONE', 'NUCCIO'),
  ('BERTONE', 'RAMARRO'),
  ('BERTONE', 'RUNABOUT'),
  ('BERTONE', 'SLALOM'),
  ('BERTONE', 'SUAGNA'),
  ('BERTONE', 'VILLA'),
  ('BERTONE', 'X1/9'),
  ('BERTONE', 'Z.E.R.'),
  ('BERTONE', 'ZERO'),
  ('BIRDIE', '6KSZR'),
  ('BIRDIE', 'CAR-GO'),
  ('BIRDIE', 'CAR-GO 4'),
  ('BIRDIE', 'CAR-GO 4 EXPLORER'),
  ('BIRDIE', 'CAR-GO 6'),
  ('BIRDIE', 'CAR-GO EXPLORER'),
  ('BIRDIE', 'CAR-GO XL'),
  ('BIRDIE', 'CAR-GO XL 500'),
  ('BIRDIE', 'CAR-GO XL EXPLORER'),
  ('BIRDIE', 'CRUIZE 4'),
  ('BIRDIE', 'CRUIZE 4 EXPLORER'),
  ('BIRDIE', 'CRUIZE 6'),
  ('BIRDIE', 'CRUIZE 6 EXPLORER'),
  ('BIRDIE', 'CRUIZE 8'),
  ('BIRDIE', 'CRUIZE 8 EXPLORER'),
  ('BIRDIE', 'GOLF'),
  ('BIRDIE', 'JOYRIDE 14'),
  ('BIRDIE', 'JOYRIDE 14 DELFIN'),
  ('BIRDIE', 'JOYRIDE 14 NEMO'),
  ('BIRDIE', 'JOYRIDE 14+'),
  ('BIRDIE', 'JOYRIDE 23'),
  ('BIRDIE', 'TRUCK 1000'),
  ('BIZZARRINI', '1900 GT EUROPA'),
  ('BIZZARRINI', '5300 GT CORSA'),
  ('BIZZARRINI', '5300 GT REVIVAL'),
  ('BIZZARRINI', '5300 GT SPYDER S.I.'),
  ('BIZZARRINI', '5300 GT STRADA'),
  ('BIZZARRINI', 'BZ-2001'),
  ('BIZZARRINI', 'GIOTTO'),
  ('BIZZARRINI', 'GT AMERICA 7000'),
  ('BIZZARRINI', 'MANTA'),
  ('BIZZARRINI', 'MONZA'),
  ('BIZZARRINI', 'P538'),
  ('BIZZARRINI', 'P538S'),
  ('BIZZARRINI', 'SCIABOLA'),
  ('BIZZARRINI', 'SCUDERIA P538S'),
  ('BLUECAR', 'BLUEBUS'),
  ('BLUECAR', 'BLUECAR'),
  ('BLUECAR', 'BLUECAR CARGO'),
  ('BLUECAR', 'BLUECAR PININFARINA'),
  ('BLUECAR', 'BLUESUMMER'),
  ('BLUECAR', 'BLUEUTILITY'),
  ('BMW', '1 SERIES  E81/E82/E87/E88'),
  ('BMW', '1 SERIES  F20/F21'),
  ('BMW', '1 SERIES  F40'),
  ('BMW', '1 SERIES M COUPE (E82)'),
  ('BMW', '114I'),
  ('BMW', '116D'),
  ('BMW', '116I'),
  ('BMW', '118D'),
  ('BMW', '118I'),
  ('BMW', '120D'),
  ('BMW', '120I'),
  ('BMW', '123D'),
  ('BMW', '125D'),
  ('BMW', '125I'),
  ('BMW', '128I'),
  ('BMW', '128TI'),
  ('BMW', '130I'),
  ('BMW', '135I'),
  ('BMW', '2002 TURBO'),
  ('BMW', '315'),
  ('BMW', '320'),
  ('BMW', '3200 CS'),
  ('BMW', '328'),
  ('BMW', '501'),
  ('BMW', '502'),
  ('BMW', '503'),
  ('BMW', '507'),
  ('BMW', '600'),
  ('BMW', '700'),
  ('BMW', 'I3'),
  ('BMW', 'I4'),
  ('BMW', 'I5'),
  ('BMW', 'I7'),
  ('BMW', 'I8'),
  ('BMW', 'ISETTA'),
  ('BMW', 'IX'),
  ('BMW', 'IX1'),
  ('BMW', 'IX2'),
  ('BMW', 'IX3'),
  ('BMW', 'M1'),
  ('BMW', 'M135I'),
  ('BMW', 'M135I XDRIVE'),
  ('BMW', 'M140I'),
  ('BMW', 'M140I XDRIVE'),
  ('BMW', 'M2'),
  ('BMW', 'M235I'),
  ('BMW', 'M240I'),
  ('BMW', 'M3'),
  ('BMW', 'M340I'),
  ('BMW', 'M4'),
  ('BMW', 'M5'),
  ('BMW', 'M550I'),
  ('BMW', 'M6'),
  ('BMW', 'M760LI'),
  ('BMW', 'M8'),
  ('BMW', 'M850I'),
  ('BMW', 'X1'),
  ('BMW', 'X2'),
  ('BMW', 'X3'),
  ('BMW', 'X4'),
  ('BMW', 'X5'),
  ('BMW', 'X6'),
  ('BMW', 'X7'),
  ('BMW', 'XM'),
  ('BMW', 'Z1'),
  ('BMW', 'Z3'),
  ('BMW', 'Z4'),
  ('BMW', 'Z8'),
  ('BORGWARD', 'ARABELLA'),
  ('BORGWARD', 'BX3'),
  ('BORGWARD', 'BX5'),
  ('BORGWARD', 'BX6'),
  ('BORGWARD', 'BX7'),
  ('BORGWARD', 'BX7 TS'),
  ('BORGWARD', 'HANSA 1100'),
  ('BORGWARD', 'HANSA 1500'),
  ('BORGWARD', 'HANSA 1800'),
  ('BORGWARD', 'HANSA 2400'),
  ('BORGWARD', 'ISABELLA'),
  ('BORGWARD', 'ISABELLA COUPE'),
  ('BORGWARD', 'ISABELLA TS'),
  ('BORGWARD', 'P100'),
  ('BOWLER', 'BULLDOG'),
  ('BOWLER', 'CSP 575'),
  ('BOWLER', 'CSP V8 PROTOTYPE P1'),
  ('BOWLER', 'CSP V8 PROTOTYPE P2'),
  ('BOWLER', 'DEFENDER CHALLENGE'),
  ('BOWLER', 'EXR'),
  ('BOWLER', 'EXR S'),
  ('BOWLER', 'NEMESIS'),
  ('BOWLER', 'PAJERO BOWLER'),
  ('BOWLER', 'PENNINE V6 110 PROTOTYPE'),
  ('BOWLER', 'RAPTOR'),
  ('BOWLER', 'TOMCAT 100'),
  ('BOWLER', 'TOMCAT 88'),
  ('BOWLER', 'WILDCAT 100'),
  ('BOWLER', 'WILDCAT 200'),
  ('BOWLER', 'WILDCAT 300'),
  ('BRABUS', '500'),
  ('BRABUS', '550 ADVENTURE 4X42'),
  ('BRABUS', '600'),
  ('BRABUS', '700'),
  ('BRABUS', '700 WIDESTAR'),
  ('BRABUS', '800'),
  ('BRABUS', '800 ADVENTURE XLP'),
  ('BRABUS', '800 BLACK & GOLD EDITION'),
  ('BRABUS', '850 6.0 BITURBO'),
  ('BRABUS', '900 ROCKET'),
  ('BRABUS', '900 ROCKET EDITION'),
  ('BRABUS', '900 ROCKET R'),
  ('BRABUS', '92R'),
  ('BRABUS', '92R CABRIO'),
  ('BRABUS', 'BRABUS S 900'),
  ('BRABUS', 'CLASSIC'),
  ('BRABUS', 'E V12'),
  ('BRABUS', 'G V12 900'),
  ('BRABUS', 'G63 700'),
  ('BRABUS', 'G63 800'),
  ('BRABUS', 'G65 900'),
  ('BRABUS', 'GLE 900 ROCKET EDITION'),
  ('BRABUS', 'MAYBACH 900'),
  ('BRABUS', 'ONE OF TEN'),
  ('BRABUS', 'ROCKET 1000'),
  ('BRABUS', 'ROCKET 900'),
  ('BRABUS', 'ROCKET 900 CABRIO'),
  ('BRABUS', 'SHADOW 800'),
  ('BRABUS', 'SL ROADSTER 800'),
  ('BRABUS', 'SMART FORFOUR ULTIMATE 101'),
  ('BRABUS', 'SMART FORTWO ULTIMATE 112'),
  ('BRABUS', 'SMART FORTWO ULTIMATE 125'),
  ('BRABUS', 'SMART FORTWO ULTIMATE R'),
  ('BRABUS', 'ULTIMATE E'),
  ('BRABUS', 'ULTIMATE E FACELIFT'),
  ('BRAMWITH', 'BADSWORTH'),
  ('BRAMWITH', 'BARNSDALE'),
  ('BRAMWITH', 'BRAMWITH LANDAULETTE'),
  ('BRAMWITH', 'BRAMWITH LIMOUSINE'),
  ('BRAMWITH', 'BRANTON'),
  ('BRAMWITH', 'YORK'),
  ('BRASINCA', 'GT 4200 - 1ST SERIES, PROTOTYPE'),
  ('BRASINCA', 'UIRAPURU'),
  ('BRILLIANCE', 'BC3'),
  ('BRILLIANCE', 'BS2'),
  ('BRILLIANCE', 'BS4'),
  ('BRILLIANCE', 'BS6'),
  ('BRILLIANCE', 'C3'),
  ('BRILLIANCE', 'DOLPHIN'),
  ('BRILLIANCE', 'FRV'),
  ('BRILLIANCE', 'FRV CROSS'),
  ('BRILLIANCE', 'FSV'),
  ('BRILLIANCE', 'GALENA'),
  ('BRILLIANCE', 'GRANDEUR'),
  ('BRILLIANCE', 'H220'),
  ('BRILLIANCE', 'H230'),
  ('BRILLIANCE', 'H3'),
  ('BRILLIANCE', 'H320'),
  ('BRILLIANCE', 'H330'),
  ('BRILLIANCE', 'H530'),
  ('BRILLIANCE', 'H530 EV'),
  ('BRILLIANCE', 'H7'),
  ('BRILLIANCE', 'JUNJIE'),
  ('BRILLIANCE', 'JUNJIE CROSS'),
  ('BRILLIANCE', 'JUNJIE FRV'),
  ('BRILLIANCE', 'JUNJIE FSV'),
  ('BRILLIANCE', 'JUNJIE WAGON'),
  ('BRILLIANCE', 'JUNJINE TUN'),
  ('BRILLIANCE', 'KUBAO'),
  ('BRILLIANCE', 'M1'),
  ('BRILLIANCE', 'M2'),
  ('BRILLIANCE', 'M3'),
  ('BRILLIANCE', 'SPLENDOR'),
  ('BRILLIANCE', 'TUN'),
  ('BRILLIANCE', 'V3'),
  ('BRILLIANCE', 'V5'),
  ('BRILLIANCE', 'V6'),
  ('BRILLIANCE', 'V7'),
  ('BRILLIANCE', 'X1'),
  ('BRILLIANCE', 'X3'),
  ('BRILLIANCE', 'ZHONGHUA'),
  ('BRILLIANCE', 'ZUNCHI'),
  ('BUGATTI', '16C GALIBIER'),
  ('BUGATTI', '18/3 CHIRON'),
  ('BUGATTI', 'BOLIDE'),
  ('BUGATTI', 'CENTODIECI'),
  ('BUGATTI', 'CHIRON'),
  ('BUGATTI', 'CHIRON PUR SPORT'),
  ('BUGATTI', 'CHIRON SUPER SPORT'),
  ('BUGATTI', 'CHIRON SUPER SPORT 300+'),
  ('BUGATTI', 'DIVO'),
  ('BUGATTI', 'EB 110'),
  ('BUGATTI', 'EB 110 GT'),
  ('BUGATTI', 'EB 110 SS'),
  ('BUGATTI', 'EB 112'),
  ('BUGATTI', 'EB 118'),
  ('BUGATTI', 'EB 218'),
  ('BUGATTI', 'LA VOITURE NOIRE'),
  ('BUGATTI', 'MISTRAL'),
  ('BUGATTI', 'TOURBILLON'),
  ('BUGATTI', 'TYPE 101'),
  ('BUGATTI', 'TYPE 101 ANTEM'),
  ('BUGATTI', 'TYPE 13'),
  ('BUGATTI', 'TYPE 17'),
  ('BUGATTI', 'TYPE 18'),
  ('BUGATTI', 'TYPE 22'),
  ('BUGATTI', 'TYPE 23'),
  ('BUGATTI', 'TYPE 251'),
  ('BUGATTI', 'TYPE 30'),
  ('BUGATTI', 'TYPE 32'),
  ('BUGATTI', 'TYPE 35'),
  ('BUGATTI', 'TYPE 37'),
  ('BUGATTI', 'TYPE 41 ROYALE'),
  ('BUGATTI', 'TYPE 43'),
  ('BUGATTI', 'TYPE 44'),
  ('BUGATTI', 'TYPE 46'),
  ('BUGATTI', 'TYPE 49'),
  ('BUGATTI', 'TYPE 50'),
  ('BUGATTI', 'TYPE 51'),
  ('BUGATTI', 'TYPE 52'),
  ('BUGATTI', 'TYPE 53'),
  ('BUGATTI', 'TYPE 54'),
  ('BUGATTI', 'TYPE 55'),
  ('BUGATTI', 'TYPE 56'),
  ('BUGATTI', 'TYPE 57'),
  ('BUGATTI', 'TYPE 57 ATLANTIC'),
  ('BUGATTI', 'TYPE 57C'),
  ('BUGATTI', 'TYPE 57S'),
  ('BUGATTI', 'TYPE 57SC ATLANTIC'),
  ('BUGATTI', 'TYPE 59'),
  ('BUGATTI', 'VEYRON 16.4'),
  ('BUGATTI', 'VEYRON 16.4 GRAND SPORT'),
  ('BUGATTI', 'VEYRON 16.4 SUPER SPORT'),
  ('BUGATTI', 'VEYRON GRAND SPORT VITESSE'),
  ('BUGATTI', 'VISION GRAN TURISMO'),
  ('BUICK', 'APOLLO'),
  ('BUICK', 'CASCADA'),
  ('BUICK', 'CENTURY'),
  ('BUICK', 'CENTURY CUSTOM'),
  ('BUICK', 'EIGHT'),
  ('BUICK', 'ELECTRA'),
  ('BUICK', 'ENCLAVE'),
  ('BUICK', 'ENCORE'),
  ('BUICK', 'ENCORE GX'),
  ('BUICK', 'ENSPIRE'),
  ('BUICK', 'ENVISION'),
  ('BUICK', 'ESTATE WAGON'),
  ('BUICK', 'EXCELLE'),
  ('BUICK', 'GL6'),
  ('BUICK', 'GL8'),
  ('BUICK', 'GL8 AVENIR'),
  ('BUICK', 'GS'),
  ('BUICK', 'INVICTA'),
  ('BUICK', 'LACROSSE'),
  ('BUICK', 'LESABRE'),
  ('BUICK', 'LUCERNE'),
  ('BUICK', 'PARK AVENUE'),
  ('BUICK', 'RAINIER'),
  ('BUICK', 'REATTA'),
  ('BUICK', 'REGAL'),
  ('BUICK', 'REGAL TOURX'),
  ('BUICK', 'RENDEZVOUS'),
  ('BUICK', 'RIVIERA'),
  ('BUICK', 'ROADMASTER'),
  ('BUICK', 'SKYLARK'),
  ('BUICK', 'SPECIAL'),
  ('BUICK', 'TERRAZA'),
  ('BUICK', 'VERANO'),
  ('BUICK', 'WILDCAT'),
  ('BYD', 'ATTO 3'),
  ('BYD', 'D1'),
  ('BYD', 'DESTROYER 05'),
  ('BYD', 'DOLPHIN'),
  ('BYD', 'E1'),
  ('BYD', 'E2'),
  ('BYD', 'E3'),
  ('BYD', 'E5'),
  ('BYD', 'E6'),
  ('BYD', 'FRIGATE 07'),
  ('BYD', 'HAN'),
  ('BYD', 'QIN'),
  ('BYD', 'QIN PLUS'),
  ('BYD', 'SEAGULL'),
  ('BYD', 'SEAL'),
  ('BYD', 'SEAL U'),
  ('BYD', 'SEALION 6'),
  ('BYD', 'SHARK'),
  ('BYD', 'SONG'),
  ('BYD', 'SONG PLUS'),
  ('BYD', 'SONG PRO'),
  ('BYD', 'TANG'),
  ('BYD', 'YANGWANG U8'),
  ('BYD', 'YANGWANG U9'),
  ('BYD', 'YUAN'),
  ('BYD', 'YUAN PLUS'),
  ('BYD', 'YUAN PRO'),
  ('CADILLAC', 'ALLANTE'),
  ('CADILLAC', 'ATS'),
  ('CADILLAC', 'ATS COUPE'),
  ('CADILLAC', 'ATS-V'),
  ('CADILLAC', 'BROUGHAM'),
  ('CADILLAC', 'CALAIS'),
  ('CADILLAC', 'CATERA'),
  ('CADILLAC', 'CELESTIQ'),
  ('CADILLAC', 'CIMARRON'),
  ('CADILLAC', 'CT4'),
  ('CADILLAC', 'CT4-V'),
  ('CADILLAC', 'CT5'),
  ('CADILLAC', 'CT5-V'),
  ('CADILLAC', 'CT6'),
  ('CADILLAC', 'CTS'),
  ('CADILLAC', 'CTS COUPE'),
  ('CADILLAC', 'CTS-V'),
  ('CADILLAC', 'DEVILLE'),
  ('CADILLAC', 'DTS'),
  ('CADILLAC', 'ELDORADO'),
  ('CADILLAC', 'ELR'),
  ('CADILLAC', 'ESCALADE'),
  ('CADILLAC', 'ESCALADE ESV'),
  ('CADILLAC', 'ESCALADE EXT'),
  ('CADILLAC', 'ESCALADE IQ'),
  ('CADILLAC', 'FLEETWOOD'),
  ('CADILLAC', 'FLEETWOOD BROUGHAM'),
  ('CADILLAC', 'LYRIQ'),
  ('CADILLAC', 'LYRIQ-V'),
  ('CADILLAC', 'OPTIQ'),
  ('CADILLAC', 'SEVILLE'),
  ('CADILLAC', 'SIXTY SPECIAL'),
  ('CADILLAC', 'STS'),
  ('CADILLAC', 'STS-V'),
  ('CADILLAC', 'V-SERIES.R'),
  ('CADILLAC', 'VISTIQ'),
  ('CADILLAC', 'XLR'),
  ('CADILLAC', 'XT4'),
  ('CADILLAC', 'XT5'),
  ('CADILLAC', 'XT6'),
  ('CADILLAC', 'XTS'),
  ('CASALINI', 'KERRY'),
  ('CASALINI', 'M10'),
  ('CASALINI', 'M12'),
  ('CASALINI', 'M14'),
  ('CASALINI', 'SULKY'),
  ('CASALINI', 'SULKYCAR'),
  ('CASALINI', 'YDEA'),
  ('CASALINI', 'YDEA PROGRESS'),
  ('CASALINI', 'YDEA TWIST'),
  ('CATERHAM', '21'),
  ('CATERHAM', '7 160'),
  ('CATERHAM', '7 165'),
  ('CATERHAM', '7 270'),
  ('CATERHAM', '7 275'),
  ('CATERHAM', '7 310'),
  ('CATERHAM', '7 340'),
  ('CATERHAM', '7 420'),
  ('CATERHAM', '7 485'),
  ('CATERHAM', '7 485 CSR'),
  ('CATERHAM', '7 620R'),
  ('CATERHAM', '7 620S'),
  ('CATERHAM', 'CLASSIC'),
  ('CATERHAM', 'CSR'),
  ('CATERHAM', 'CSR 175'),
  ('CATERHAM', 'CSR 200'),
  ('CATERHAM', 'SUPER SEVEN 1600'),
  ('CATERHAM', 'SUPER SEVEN 2000'),
  ('CATERHAM', 'SUPER SEVEN 600'),
  ('CATERHAM', 'SUPERLIGHT'),
  ('CATERHAM', 'SUPERLIGHT R300'),
  ('CATERHAM', 'SUPERLIGHT R400'),
  ('CATERHAM', 'SUPERLIGHT R500'),
  ('CATERHAM', 'SUPERLIGHT R500 DURATEC'),
  ('CENTTRO', 'AVANTIER C'),
  ('CENTTRO', 'CITYPORTER'),
  ('CENTTRO', 'LOGIMAX'),
  ('CENTTRO', 'LOGISTAR 100'),
  ('CENTTRO', 'LOGISTAR 200'),
  ('CENTTRO', 'LOGISTAR 260'),
  ('CENTTRO', 'LOGISTAR 400'),
  ('CENTTRO', 'LOGISTAR 400C'),
  ('CENTTRO', 'LOGISTAR 500'),
  ('CENTTRO', 'LOGISTAR 600'),
  ('CENTTRO', 'METRO'),
  ('CENTTRO', 'N-SERIES'),
  ('CENTTRO', 'T-CLASS'),
  ('CENTTRO', 'TANGO'),
  ('CHATENET', 'BAROODER'),
  ('CHATENET', 'CH26'),
  ('CHATENET', 'CH26 SPRING'),
  ('CHATENET', 'CH30'),
  ('CHATENET', 'CH32'),
  ('CHATENET', 'CH40'),
  ('CHATENET', 'CH46'),
  ('CHATENET', 'CH46 ELECTRIC'),
  ('CHATENET', 'CH46 R'),
  ('CHATENET', 'CH46 SPORT'),
  ('CHATENET', 'CH50'),
  ('CHATENET', 'MEDIA'),
  ('CHATENET', 'SPEEDINO'),
  ('CHESIL', 'CHESIL SPEEDSTER 356'),
  ('CHESIL', 'CHESIL SPEEDSTER 356 ELECTRIC'),
  ('CHESIL', 'SPEEDSTER 356'),
  ('CHEVROLET', 'CORVETTE C1'),
  ('CHEVROLET', 'CORVETTE C2 STING RAY'),
  ('CHEVROLET', 'CORVETTE C3'),
  ('CHEVROLET', 'CORVETTE C4'),
  ('CHEVROLET', 'CORVETTE C5'),
  ('CHEVROLET', 'CORVETTE C6'),
  ('CHEVROLET', 'CORVETTE C7'),
  ('CHEVROLET', 'CORVETTE C8'),
  ('CHEVROLET', 'CORVETTE CALLAWAY C12'),
  ('CHEVROLET', 'CORVETTE CALLAWAY TWIN TURBO (C4)'),
  ('CHEVROLET', 'CORVETTE CERV II PROTOTYPE'),
  ('CHEVROLET', 'CORVETTE CERV III PROTOTYPE'),
  ('CHEVROLET', 'CORVETTE GRAND SPORT (C2)'),
  ('CHEVROLET', 'CORVETTE GRAND SPORT (C4)'),
  ('CHEVROLET', 'CORVETTE GRAND SPORT (C6)'),
  ('CHEVROLET', 'CORVETTE GRAND SPORT (C7)'),
  ('CHEVROLET', 'CORVETTE MANTA RAY CONCEPT'),
  ('CHEVROLET', 'CORVETTE ZORA PROTOTYPE (CERV I)'),
  ('CHEVROLET (EU)', 'AVEO'),
  ('CHEVROLET (EU)', 'CAPTIVA'),
  ('CHEVROLET (EU)', 'CRUZE'),
  ('CHEVROLET (EU)', 'EPICA'),
  ('CHEVROLET (EU)', 'EVANDA'),
  ('CHEVROLET (EU)', 'KALOS'),
  ('CHEVROLET (EU)', 'LACETTI'),
  ('CHEVROLET (EU)', 'MATIZ'),
  ('CHEVROLET (EU)', 'ORLANDO'),
  ('CHEVROLET (EU)', 'REZZO'),
  ('CHEVROLET (EU)', 'SPARK'),
  ('CHEVROLET (EU)', 'TACUMA'),
  ('CHEVROLET (EU)', 'TRAX'),
  ('CHEVROLET (USA)', 'ASTRO'),
  ('CHEVROLET (USA)', 'AVALANCHE'),
  ('CHEVROLET (USA)', 'AVEO'),
  ('CHEVROLET (USA)', 'BEL AIR'),
  ('CHEVROLET (USA)', 'BERETTA'),
  ('CHEVROLET (USA)', 'BISCAYNE'),
  ('CHEVROLET (USA)', 'BLAZER'),
  ('CHEVROLET (USA)', 'BOLT EV'),
  ('CHRYSLER', '200'),
  ('CHRYSLER', '300'),
  ('CHRYSLER', '300C'),
  ('CHRYSLER', '300M'),
  ('CHRYSLER', 'AIRFLOW'),
  ('CHRYSLER', 'ASPEN'),
  ('CHRYSLER', 'ATLANTIC CONCEPT'),
  ('CHRYSLER', 'CIRRUS'),
  ('CHRYSLER', 'CONCORDE'),
  ('CHRYSLER', 'CORDOBA'),
  ('CHRYSLER', 'CROSSFIRE'),
  ('CHRYSLER', 'DAYTONA'),
  ('CHRYSLER', 'DYNASTY'),
  ('CHRYSLER', 'E-CLASS'),
  ('CHRYSLER', 'FIFTH AVENUE'),
  ('CHRYSLER', 'IMPERIAL'),
  ('CHRYSLER', 'IMPERIAL (1990S)'),
  ('CHRYSLER', 'INTREPID'),
  ('CHRYSLER', 'LASER'),
  ('CHRYSLER', 'LEBARON'),
  ('CHRYSLER', 'LHS'),
  ('CHRYSLER', 'NEON'),
  ('CHRYSLER', 'NEW YORKER'),
  ('CHRYSLER', 'NEWPORT'),
  ('CHRYSLER', 'PACIFICA'),
  ('CHRYSLER', 'PHAETON CONCEPT'),
  ('CHRYSLER', 'PROWLER'),
  ('CHRYSLER', 'PT CRUISER'),
  ('CHRYSLER', 'SARATOGA'),
  ('CHRYSLER', 'SEBRING'),
  ('CHRYSLER', 'STRATUS'),
  ('CHRYSLER', 'TC BY MASERATI'),
  ('CHRYSLER', 'TOWN & COUNTRY'),
  ('CHRYSLER', 'VALIANT'),
  ('CHRYSLER', 'VISION'),
  ('CHRYSLER', 'VOYAGER'),
  ('CHRYSLER', 'WINDSOR'),
  ('CITROEN', '2CV'),
  ('CITROEN', 'ACADIANE'),
  ('CITROEN', 'AMI'),
  ('CITROEN', 'AX'),
  ('CITROEN', 'BERLINGO'),
  ('CITROEN', 'BX'),
  ('CITROEN', 'C1'),
  ('CITROEN', 'C3'),
  ('CITROEN', 'C3 AIRCROSS'),
  ('CITROEN', 'C4 CACTUS'),
  ('CITROEN', 'C4 PICASSO'),
  ('CITROEN', 'C4 X'),
  ('CITROEN', 'C5 AIRCROSS'),
  ('CITROEN', 'C5 X'),
  ('CITROEN', 'C6'),
  ('CITROEN', 'C8'),
  ('CITROEN', 'CX'),
  ('CITROEN', 'CX PRESTIGE'),
  ('CITROEN', 'DS'),
  ('CITROEN', 'DYANE'),
  ('CITROEN', 'E-C4'),
  ('CITROEN', 'E-MEHARI'),
  ('CITROEN', 'GS'),
  ('CITROEN', 'GSA'),
  ('CITROEN', 'JUMPER'),
  ('CITROEN', 'JUMPY'),
  ('CITROEN', 'MEHARI'),
  ('CITROEN', 'NEMO'),
  ('CITROEN', 'ROSALIE'),
  ('CITROEN', 'SAXO'),
  ('CITROEN', 'SPACETOURER'),
  ('CITROEN', 'TRACTION AVANT'),
  ('CITROEN', 'VISA'),
  ('CITROEN', 'XANTIA'),
  ('CITROEN', 'XM'),
  ('CITROEN', 'XSARA'),
  ('CITROEN', 'XSARA PICASSO'),
  ('CITROEN', 'ZX'),
  ('COBRA', 'AC COBRA 260'),
  ('COBRA', 'AC COBRA 289'),
  ('COBRA', 'AC COBRA 289 FIA'),
  ('COBRA', 'AC COBRA 289 STREET'),
  ('COBRA', 'AC COBRA 427'),
  ('COBRA', 'AC COBRA 427 COMPETITION'),
  ('COBRA', 'AC COBRA 427 S/C'),
  ('COBRA', 'COBRA DAYTONA COUPE'),
  ('COBRA', 'COBRA MKIII'),
  ('COBRA', 'COBRA MKIV'),
  ('COBRA', 'COBRA SUPER SNAKE'),
  ('COBRA', 'CSX2000'),
  ('COBRA', 'CSX3000'),
  ('CORBIN', 'MERLIN ROADSTER'),
  ('CORBIN', 'SPARROW'),
  ('CORBIN', 'SPARROW II (NMG2)'),
  ('CUPRA', 'ATECA'),
  ('CUPRA', 'BORN'),
  ('CUPRA', 'FORMENTOR'),
  ('CUPRA', 'FORMENTOR VZ5'),
  ('CUPRA', 'LEON'),
  ('CUPRA', 'LEON SPORTSTOURER'),
  ('CUPRA', 'RAVAL'),
  ('CUPRA', 'TAVASCAN'),
  ('CUPRA', 'TERRAMAR'),
  ('DACIA', '1100'),
  ('DACIA', '1300'),
  ('DACIA', '1310'),
  ('DACIA', '1325 LIBERTA'),
  ('DACIA', 'BIGSTER'),
  ('DACIA', 'DOKKER'),
  ('DACIA', 'DUSTER'),
  ('DACIA', 'JOGGER'),
  ('DACIA', 'LODGY'),
  ('DACIA', 'LOGAN'),
  ('DACIA', 'LOGAN MCV'),
  ('DACIA', 'NOVA'),
  ('DACIA', 'SANDERO'),
  ('DACIA', 'SANDERO STEPWAY'),
  ('DACIA', 'SOLENZA'),
  ('DACIA', 'SPRING'),
  ('DACIA', 'SUPERNOVA'),
  ('DAEWOO', 'ALPHEON'),
  ('DAEWOO', 'ARCADIA'),
  ('DAEWOO', 'CHAIRMAN'),
  ('DAEWOO', 'CHAIRMAN W'),
  ('DAEWOO', 'CIELO'),
  ('DAEWOO', 'DAMAS'),
  ('DAEWOO', 'ESPERO'),
  ('DAEWOO', 'GENTRA'),
  ('DAEWOO', 'ISTANA'),
  ('DAEWOO', 'KALOS'),
  ('DAEWOO', 'LANOS'),
  ('DAEWOO', 'LEGANZA'),
  ('DAEWOO', 'MATIZ'),
  ('DAEWOO', 'MUSSO'),
  ('DAEWOO', 'NUBIRA'),
  ('DAEWOO', 'REZZO'),
  ('DAEWOO', 'TICO'),
  ('DAEWOO', 'WINSTORM'),
  ('DAIHATSU', 'ALTIS'),
  ('DAIHATSU', 'APPLAUSE'),
  ('DAIHATSU', 'ATRAI'),
  ('DAIHATSU', 'AYLA'),
  ('DAIHATSU', 'BE-GO'),
  ('DAIHATSU', 'BOON'),
  ('DAIHATSU', 'CAST'),
  ('DAIHATSU', 'CHARADE'),
  ('DAIHATSU', 'CHARMANT'),
  ('DAIHATSU', 'COO'),
  ('DAIHATSU', 'COPEN'),
  ('DAIHATSU', 'CUORE'),
  ('DAIHATSU', 'DELTA'),
  ('DAIHATSU', 'ESSE'),
  ('DAIHATSU', 'FEROZA'),
  ('DAIHATSU', 'GRAN MAX'),
  ('DAIHATSU', 'HIJET'),
  ('DAIHATSU', 'LEEZA'),
  ('DAIHATSU', 'MATERIA'),
  ('DAIHATSU', 'MAX'),
  ('DAIHATSU', 'MEBIUS'),
  ('DAIHATSU', 'MIRA'),
  ('DAIHATSU', 'MOVE'),
  ('DAIHATSU', 'NAKED'),
  ('DAIHATSU', 'OPTI'),
  ('DAIHATSU', 'PYZAR'),
  ('DAIHATSU', 'RUGGER'),
  ('DAIHATSU', 'SONICA'),
  ('DAIHATSU', 'TERIOS'),
  ('DAIHATSU', 'WAKE'),
  ('DAIHATSU', 'XENIA'),
  ('DAIMLER', '15'),
  ('DAIMLER', '16'),
  ('DAIMLER', '20'),
  ('DAIMLER', '25'),
  ('DAIMLER', '30'),
  ('DAIMLER', '35'),
  ('DAIMLER', '45'),
  ('DAIMLER', '50'),
  ('DAIMLER', 'CENTURY'),
  ('DAIMLER', 'CONQUEST'),
  ('DAIMLER', 'CONQUEST CENTURY'),
  ('DAIMLER', 'CONQUEST ROADSTER'),
  ('DAIMLER', 'CONSORT'),
  ('DAIMLER', 'CORSICA'),
  ('DAIMLER', 'DB18'),
  ('DAIMLER', 'DE27'),
  ('DAIMLER', 'DE36'),
  ('DAIMLER', 'DK400'),
  ('DAIMLER', 'DOUBLE-SIX'),
  ('DAIMLER', 'DR450'),
  ('DAIMLER', 'EMPRESS'),
  ('DAIMLER', 'LIGHT TWENTY'),
  ('DAIMLER', 'MAJESTIC'),
  ('DAIMLER', 'MAJESTIC MAJOR'),
  ('DAIMLER', 'ONE-O-FOUR'),
  ('DAIMLER', 'REGENCY'),
  ('DAIMLER', 'REGENCY MK II'),
  ('DAIMLER', 'REGENCY MK III'),
  ('DAIMLER', 'SOVEREIGN'),
  ('DAIMLER', 'SP250'),
  ('DAIMLER', 'SPECIAL SPORTS'),
  ('DAIMLER', 'STRAIGHT EIGHT'),
  ('DAIMLER', 'V8-250'),
  ('DATSUN', '100A'),
  ('DATSUN', '120Y'),
  ('DATSUN', '140J'),
  ('DATSUN', '140Y'),
  ('DATSUN', '160B'),
  ('DATSUN', '160J'),
  ('DATSUN', '180B'),
  ('DATSUN', '200B'),
  ('DATSUN', '200C'),
  ('DATSUN', '200SX'),
  ('DATSUN', '210'),
  ('DATSUN', '211'),
  ('DATSUN', '240Z'),
  ('DATSUN', '260Z'),
  ('DATSUN', '280Z'),
  ('DATSUN', '280ZX'),
  ('DATSUN', '300ZX'),
  ('DATSUN', 'BLUEBIRD'),
  ('DATSUN', 'CHERRY'),
  ('DATSUN', 'CROSS'),
  ('DATSUN', 'FAIRLADY'),
  ('DATSUN', 'GO'),
  ('DATSUN', 'GO+'),
  ('DATSUN', 'LAUREL'),
  ('DATSUN', 'MI-DO'),
  ('DATSUN', 'ON-DO'),
  ('DATSUN', 'REDI-GO'),
  ('DATSUN', 'ROADSTER'),
  ('DATSUN', 'STANZA'),
  ('DATSUN', 'SUNNY'),
  ('DATSUN', 'VIOLET'),
  ('DAX', '427'),
  ('DAX', 'CALIFORNIAN'),
  ('DAX', 'KAMALA'),
  ('DAX', 'RUSH'),
  ('DAX', 'TOJEIRO'),
  ('DE TOMASO', 'BIGUA'),
  ('DE TOMASO', 'DE TOMASO 5000'),
  ('DE TOMASO', 'DEAUVILLE'),
  ('DE TOMASO', 'GUARA'),
  ('DE TOMASO', 'LONGCHAMP'),
  ('DE TOMASO', 'MANGUSTA'),
  ('DE TOMASO', 'P70'),
  ('DE TOMASO', 'P72'),
  ('DE TOMASO', 'P900'),
  ('DE TOMASO', 'PANTERA'),
  ('DE TOMASO', 'SPORT 2000'),
  ('DE TOMASO', 'SPORT 5000'),
  ('DE TOMASO', 'VALLELUNGA'),
  ('DELAHAYE', '134'),
  ('DELAHAYE', '134N'),
  ('DELAHAYE', '135'),
  ('DELAHAYE', '135M'),
  ('DELAHAYE', '135MS'),
  ('DELAHAYE', '138'),
  ('DELAHAYE', '145'),
  ('DELAHAYE', '148'),
  ('DELAHAYE', '148L'),
  ('DELAHAYE', '155'),
  ('DELAHAYE', '165'),
  ('DELAHAYE', '168'),
  ('DELAHAYE', '171'),
  ('DELAHAYE', '175'),
  ('DELAHAYE', '178'),
  ('DELAHAYE', '18 SPORT'),
  ('DELAHAYE', '180'),
  ('DELAHAYE', '235'),
  ('DELAHAYE', '44'),
  ('DELAHAYE', 'TYPE 0'),
  ('DELAHAYE', 'TYPE 1'),
  ('DELAHAYE', 'TYPE 2'),
  ('DELAHAYE', 'VLR'),
  ('DELOREAN', 'DMC-12'),
  ('DFSK', 'C31'),
  ('DFSK', 'C35'),
  ('DFSK', 'C36'),
  ('DFSK', 'C37'),
  ('DFSK', 'EC35'),
  ('DFSK', 'EC36'),
  ('DFSK', 'EC36II'),
  ('DFSK', 'FENGON 500'),
  ('DFSK', 'FENGON 580'),
  ('DFSK', 'FENGON 600'),
  ('DFSK', 'FENGON IX5'),
  ('DFSK', 'FENGON IX6'),
  ('DFSK', 'FENGON IX7'),
  ('DFSK', 'GLORY 330'),
  ('DFSK', 'GLORY 370'),
  ('DFSK', 'GLORY 500'),
  ('DFSK', 'GLORY 560'),
  ('DFSK', 'GLORY 580'),
  ('DFSK', 'K01'),
  ('DFSK', 'K02'),
  ('DFSK', 'K05'),
  ('DFSK', 'K07'),
  ('DFSK', 'K07S'),
  ('DFSK', 'K17'),
  ('DODGE', 'ARIES'),
  ('DODGE', 'ASPEN'),
  ('DODGE', 'AVENGER'),
  ('DODGE', 'CALIBER'),
  ('DODGE', 'CARAVAN'),
  ('DODGE', 'CHALLENGER'),
  ('DODGE', 'CHARGER'),
  ('DODGE', 'COLT'),
  ('DODGE', 'CORONET'),
  ('DODGE', 'DAKOTA'),
  ('DODGE', 'DART'),
  ('DODGE', 'DAYTONA'),
  ('DODGE', 'DIPLOMAT'),
  ('DODGE', 'DURANGO'),
  ('DODGE', 'GRAND CARAVAN'),
  ('DODGE', 'HORNET'),
  ('DODGE', 'INTREPID'),
  ('DODGE', 'JOURNEY'),
  ('DODGE', 'LANCER'),
  ('DODGE', 'MAGNUM'),
  ('DODGE', 'MIRADA'),
  ('DODGE', 'MONACO'),
  ('DODGE', 'NEON'),
  ('DODGE', 'NITRO'),
  ('DODGE', 'OMNI'),
  ('DODGE', 'POLARA'),
  ('DODGE', 'RAIDER'),
  ('DODGE', 'RAM'),
  ('DODGE', 'RAM VAN'),
  ('DODGE', 'RAMCHARGER'),
  ('DODGE', 'SHADOW'),
  ('DODGE', 'SPIRIT'),
  ('DODGE', 'STEALTH'),
  ('DODGE', 'STRATUS'),
  ('DODGE', 'SUPER BEE'),
  ('DODGE', 'VIPER'),
  ('DONKERVOORT', 'D10'),
  ('DONKERVOORT', 'D8'),
  ('DONKERVOORT', 'D8 COSWORTH'),
  ('DONKERVOORT', 'D8 GTO'),
  ('DONKERVOORT', 'D8 ZETEC'),
  ('DONKERVOORT', 'F22'),
  ('DONKERVOORT', 'S8'),
  ('DR AUTOMOBILES', 'DR 1'),
  ('DR AUTOMOBILES', 'DR 1.0'),
  ('DR AUTOMOBILES', 'DR 1.0 EV'),
  ('DR AUTOMOBILES', 'DR 2'),
  ('DR AUTOMOBILES', 'DR 2 EV'),
  ('DR AUTOMOBILES', 'DR 3 EV'),
  ('DR AUTOMOBILES', 'DR 3.0'),
  ('DR AUTOMOBILES', 'DR 4.0'),
  ('DR AUTOMOBILES', 'DR 5.0'),
  ('DR AUTOMOBILES', 'DR 5.0 EV'),
  ('DR AUTOMOBILES', 'DR 6.0'),
  ('DR AUTOMOBILES', 'DR 7.0'),
  ('DR AUTOMOBILES', 'DR CITYCROSS'),
  ('DR AUTOMOBILES', 'DR F35'),
  ('DR AUTOMOBILES', 'DR PK8'),
  ('DR AUTOMOBILES', 'DR ZERO');


WITH distinct_makes AS (
  SELECT DISTINCT make FROM inventory_car_seed
)
INSERT INTO inventory_car_makes (company_id, subcategory_id, name, code)
SELECT NULL, NULL, dm.make, dm.make
FROM distinct_makes dm
WHERE NOT EXISTS (
  SELECT 1 FROM inventory_car_makes m
  WHERE m.company_id IS NULL AND m.subcategory_id IS NULL AND m.name = dm.make
);

WITH distinct_models AS (
  SELECT DISTINCT make, model FROM inventory_car_seed
)
INSERT INTO inventory_car_models (company_id, make_id, name, code)
SELECT NULL, mk.id, dm.model, dm.model
FROM distinct_models dm
JOIN inventory_car_makes mk
  ON mk.company_id IS NULL AND mk.subcategory_id IS NULL AND mk.name = dm.make
WHERE NOT EXISTS (
  SELECT 1 FROM inventory_car_models mdl
  WHERE mdl.company_id IS NULL AND mdl.make_id = mk.id AND mdl.name = dm.model
);

INSERT INTO inventory_model_years (company_id, model_id, year)
SELECT NULL, mdl.id, y.year
FROM inventory_car_models mdl
JOIN inventory_car_makes mk ON mk.id = mdl.make_id
CROSS JOIN generate_series(1980, 2026) AS y(year)
WHERE mdl.company_id IS NULL AND mk.company_id IS NULL AND mk.subcategory_id IS NULL
  AND NOT EXISTS (
    SELECT 1 FROM inventory_model_years yr
    WHERE yr.company_id IS NULL AND yr.model_id = mdl.id AND yr.year = y.year
  );

DROP TABLE inventory_car_seed;
